run:
  concurrency: 4
  timeout: 5m
  issues-exit-code: 2
  tests: false

output:
  print-issued-lines: false
  print-linter-name: true
  uniq-by-line: false
  path-prefix: ""
  sort-results: true

linters:
  disable-all: true

  enable:
    - staticcheck
    - gosimple
    - govet
    - revive
    - stylecheck
    - forcetypeassert
    - gocritic
    - wsl
